CREATE DATABASE application;
USE application;
CREATE TABLE `users` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`USERNAME` CHAR(50) NOT NULL,
	`EMAIL` CHAR(50) NOT NULL,
	`NAME` CHAR(50) NOT NULL,
	`PASSWORD` CHAR(60) NOT NULL,
	primary key (ID)
);
